package com.proj.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-04-19T16:35:26.624+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://impl.webservice.proj.com/", name = "SyncDataService")
@XmlSeeAlso({ObjectFactory.class})
public interface SyncDataService {

    @WebMethod
    @RequestWrapper(localName = "syncProductionCode", targetNamespace = "http://impl.webservice.proj.com/", className = "SyncProductionCode")
    @ResponseWrapper(localName = "syncProductionCodeResponse", targetNamespace = "http://impl.webservice.proj.com/", className = "SyncProductionCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String syncProductionCode(
            @WebParam(name = "data", targetNamespace = "http://impl.webservice.proj.com/")
                    String data
    );

    @WebMethod
    @RequestWrapper(localName = "syncSeries", targetNamespace = "http://impl.webservice.proj.com/", className = "SyncSeries")
    @ResponseWrapper(localName = "syncSeriesResponse", targetNamespace = "http://impl.webservice.proj.com/", className = "SyncSeriesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String syncSeries(
            @WebParam(name = "data", targetNamespace = "http://impl.webservice.proj.com/")
                    String data
    );

    @WebMethod
    @RequestWrapper(localName = "syncMaterial", targetNamespace = "http://impl.webservice.proj.com/", className = "SyncMaterial")
    @ResponseWrapper(localName = "syncMaterialResponse", targetNamespace = "http://impl.webservice.proj.com/", className = "SyncMaterialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String syncMaterial(
            @WebParam(name = "data", targetNamespace = "http://impl.webservice.proj.com/")
                    String data
    );
}
