
package com.proj.webservice.impl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-04-19T16:35:26.587+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class SyncDataService_SyncDataServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.proj.com/", "syncData");

    private SyncDataService_SyncDataServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SyncData.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SyncData ss = new SyncData(wsdlURL, SERVICE_NAME);
        SyncDataService port = ss.getSyncDataServiceImplPort();  
        
        {
        System.out.println("Invoking syncProductionCode...");
        String _syncProductionCode_data = "";
        String _syncProductionCode__return = port.syncProductionCode(_syncProductionCode_data);
        System.out.println("syncProductionCode.result=" + _syncProductionCode__return);


        }
        {
        System.out.println("Invoking syncSeries...");
        String _syncSeries_data = "";
        String _syncSeries__return = port.syncSeries(_syncSeries_data);
        System.out.println("syncSeries.result=" + _syncSeries__return);


        }
        {
        System.out.println("Invoking syncMaterial...");
        String _syncMaterial_data = "";
        String _syncMaterial__return = port.syncMaterial(_syncMaterial_data);
        System.out.println("syncMaterial.result=" + _syncMaterial__return);


        }

        System.exit(0);
    }

}
